#!/bin/bash
#set -x
# Setup:
# 1	-	https://github.com/andreafabrizi/Dropbox-Uploader
# 2 - sudo vi /usr/local/sbin/raccessd
# 3 - sudo chmod +x /usr/local/sbin/raccessd
# 4 - crontab -e
# 5 - */5 * * * *  /usr/local/sbin/raccessd monitor
#

#
# Var definitions
#
NAME=`hostname`                 #indentificator of your host
OUTPUT_FILE="$HOME/tmate.url"   #file where connection string is stored
DROPBOX_UPLOADER="/usr/local/sbin/dropbox_uploader.sh"

TMATE=`which tmate`

#
#Functions
#
START(){
  $TMATE -S /tmp/tmate.sock new-session -d               # Launch tmate in a detached state
  $TMATE -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
  NOTIFY
}

STOP(){
  ps -ef | grep tmate | awk '{print $2}' | xargs kill -9
}

PROCMON(){
  STATUS=`ps -ef | grep tmate | grep -v grep | wc -l`
  # STATUS = 0 means that has no processes running:
  if [ "$STATUS" == 0 ]; then
          START
  fi
  NOTIFY
}

NOTIFY(){
  CONNSTR=`$TMATE -S /tmp/tmate.sock display -p '#{tmate_ssh}'`
	if [ "$?" == "1" ]; then
		START
		exit 0
	fi
  OLD_CONNSTR=`cat $OUTPUT_FILE`
  if [ "$OLD_CONNSTR" != "$CONNSTR" ]; then
    echo "$CONNSTR" > $OUTPUT_FILE
		$DROPBOX_UPLOADER upload tmate.url tmate.url.$NAME
  fi
}

#
# Script options
#
case $1 in
  start)
    START
    ;;

  stop)
    STOP
    ;;

  restart)
    STOP
    START
    ;;

  monitor)
	  PROCMON
	  ;;

  notify)
    NOTIFY
    ;;

  *)
    echo -e "Try $0 {start|stop|monitor|notify|restart}"
    ;;
esac
